<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PageListTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        DB::table('page_list')->delete();
        
        DB::table('page_list')->insert(array (
            0 => 
            array (
                'res_id' => 'AA',
                'title' => 'Role  List',
                'controller_title' => '05. User Settings',
                'directory' => 'admin',
                'controller' => 'app-permission',
                'method' => 'role-list',
                'panel' => 'A',
                'status' => 'A',
            ),
            1 => 
            array (
                'res_id' => 'AB',
                'title' => 'Role Access',
                'controller_title' => '05. User Settings',
                'directory' => 'admin',
                'controller' => 'app-permission',
                'method' => 'role-access',
                'panel' => 'A',
                'status' => 'A',
            ),
            2 => 
            array (
                'res_id' => 'AC',
                'title' => 'New Role',
                'controller_title' => '05. User Settings',
                'directory' => 'admin',
                'controller' => 'app-permission',
                'method' => 'role-add',
                'panel' => 'A',
                'status' => 'A',
            ),
            3 => 
            array (
                'res_id' => 'AD',
                'title' => 'Edit Role',
                'controller_title' => '05. User Settings',
                'directory' => 'admin',
                'controller' => 'app-permission',
                'method' => 'role-edit',
                'panel' => 'A',
                'status' => 'A',
            ),
            4 => 
            array (
                'res_id' => 'AE',
                'title' => 'Change Role Access',
                'controller_title' => '05. User Settings',
                'directory' => 'admin',
                'controller' => 'app-permission-confirm',
                'method' => 'change-role-access',
                'panel' => 'A',
                'status' => 'A',
            ),
            5 => 
            array (
                'res_id' => 'AF',
                'title' => 'Resource',
                'controller_title' => '05. User Settings',
                'directory' => 'admin',
                'controller' => 'app-permission',
                'method' => 'change-page-title',
                'panel' => 'A',
                'status' => 'H',
            ),
            6 => 
            array (
                'res_id' => 'AG',
                'title' => 'Setting List',
                'controller_title' => 'App Setting',
                'directory' => 'admin',
                'controller' => 'app-setting',
                'method' => 'index',
                'panel' => 'A',
                'status' => 'H',
            ),
            7 => 
            array (
                'res_id' => 'AH',
                'title' => 'New Setting',
                'controller_title' => 'App Setting',
                'directory' => 'admin',
                'controller' => 'app-setting',
                'method' => 'add',
                'panel' => 'A',
                'status' => 'H',
            ),
            8 => 
            array (
                'res_id' => 'AI',
                'title' => 'User List',
                'controller_title' => '05. User Settings',
                'directory' => 'admin',
                'controller' => 'app-permission',
                'method' => 'user-list',
                'panel' => 'A',
                'status' => 'A',
            ),
            9 => 
            array (
                'res_id' => 'AJ',
                'title' => 'Dashboard',
                'controller_title' => '08. My Dashboard',
                'directory' => 'admin',
                'controller' => 'dashboard',
                'method' => 'index',
                'panel' => 'A',
                'status' => 'S',
            ),
            10 => 
            array (
                'res_id' => 'AK',
                'title' => 'Update User',
                'controller_title' => '05. User Settings',
                'directory' => 'admin',
                'controller' => 'app-permission',
                'method' => 'add-edit-appuser',
                'panel' => 'A',
                'status' => 'A',
            ),
            11 => 
            array (
                'res_id' => 'AL',
                'title' => 'Category List',
                'controller_title' => '12. Category',
                'directory' => 'admin',
                'controller' => 'category',
                'method' => 'index',
                'panel' => 'A',
                'status' => 'A',
            ),
            12 => 
            array (
                'res_id' => 'AM',
                'title' => 'New Category',
                'controller_title' => '12. Category',
                'directory' => 'admin',
                'controller' => 'category',
                'method' => 'add',
                'panel' => 'A',
                'status' => 'A',
            ),
            13 => 
            array (
                'res_id' => 'AN',
                'title' => 'Edit Category',
                'controller_title' => '12. Category',
                'directory' => 'admin',
                'controller' => 'category',
                'method' => 'edit',
                'panel' => 'A',
                'status' => 'A',
            ),
            14 => 
            array (
                'res_id' => 'AO',
                'title' => 'Status Change',
                'controller_title' => '12. Category',
                'directory' => 'admin',
                'controller' => 'category-confirm',
                'method' => 'status-change',
                'panel' => 'A',
                'status' => 'A',
            ),
            15 => 
            array (
                'res_id' => 'AP',
                'title' => 'Knowledge List',
                'controller_title' => '11. Knowledge',
                'directory' => 'admin',
                'controller' => 'knowledge',
                'method' => 'index',
                'panel' => 'A',
                'status' => 'A',
            ),
            16 => 
            array (
                'res_id' => 'AQ',
                'title' => 'New Knowledge',
                'controller_title' => '11. Knowledge',
                'directory' => 'admin',
                'controller' => 'knowledge',
                'method' => 'add',
                'panel' => 'A',
                'status' => 'A',
            ),
            17 => 
            array (
                'res_id' => 'AR',
                'title' => 'Ticket List',
                'controller_title' => '10. Ticket',
                'directory' => 'admin',
                'controller' => 'ticket',
                'method' => 'index',
                'panel' => 'A',
                'status' => 'A',
            ),
            18 => 
            array (
                'res_id' => 'AS',
                'title' => 'New Ticket',
                'controller_title' => '10. Ticket',
                'directory' => 'admin',
                'controller' => 'ticket',
                'method' => 'add',
                'panel' => 'A',
                'status' => 'H',
            ),
            19 => 
            array (
                'res_id' => 'AT',
                'title' => 'Role Delete',
                'controller_title' => '05. User Settings',
                'directory' => 'admin',
                'controller' => 'app-permission-confirm',
                'method' => 'role-delete',
                'panel' => 'A',
                'status' => 'A',
            ),
            20 => 
            array (
                'res_id' => 'AU',
                'title' => 'Edit Knowledge',
                'controller_title' => '11. Knowledge',
                'directory' => 'admin',
                'controller' => 'knowledge',
                'method' => 'edit',
                'panel' => 'A',
                'status' => 'A',
            ),
            21 => 
            array (
                'res_id' => 'AV',
                'title' => 'Status Change',
                'controller_title' => '11. Knowledge',
                'directory' => 'admin',
                'controller' => 'knowledge-confirm',
                'method' => 'status-change',
                'panel' => 'A',
                'status' => 'A',
            ),
            22 => 
            array (
                'res_id' => 'AW',
                'title' => 'Index',
                'controller_title' => 'Site',
                'directory' => '',
                'controller' => 'site',
                'method' => 'index',
                'panel' => 'C',
                'status' => 'A',
            ),
            23 => 
            array (
                'res_id' => 'AX',
                'title' => 'Not Found',
                'controller_title' => 'Site',
                'directory' => '',
                'controller' => 'site',
                'method' => 'knowledge',
                'panel' => 'C',
                'status' => 'A',
            ),
            24 => 
            array (
                'res_id' => 'AY',
                'title' => 'About Support System',
                'controller_title' => 'Knowledge',
                'directory' => '',
                'controller' => 'knowledge',
                'method' => 'details',
                'panel' => 'C',
                'status' => 'A',
            ),
            25 => 
            array (
                'res_id' => 'AZ',
                'title' => 'Counter',
                'controller_title' => 'Knowledge',
                'directory' => '',
                'controller' => 'knowledge',
                'method' => 'counter',
                'panel' => 'C',
                'status' => 'A',
            ),
            26 => 
            array (
                'res_id' => 'BA',
                'title' => 'Index',
                'controller_title' => 'Hauth',
                'directory' => '',
                'controller' => 'hauth',
                'method' => 'index',
                'panel' => 'C',
                'status' => 'A',
            ),
            27 => 
            array (
                'res_id' => 'BB',
                'title' => 'Window',
                'controller_title' => 'Hauth',
                'directory' => '',
                'controller' => 'hauth',
                'method' => 'window',
                'panel' => 'C',
                'status' => 'A',
            ),
            28 => 
            array (
                'res_id' => 'BC',
                'title' => 'Endpoint',
                'controller_title' => 'Hauth',
                'directory' => '',
                'controller' => 'hauth',
                'method' => 'endpoint',
                'panel' => 'C',
                'status' => 'A',
            ),
            29 => 
            array (
                'res_id' => 'BD',
                'title' => 'Index',
                'controller_title' => 'Social',
                'directory' => '',
                'controller' => 'social',
                'method' => 'index',
                'panel' => 'C',
                'status' => 'A',
            ),
            30 => 
            array (
                'res_id' => 'BE',
                'title' => 'Login',
                'controller_title' => 'Social',
                'directory' => '',
                'controller' => 'social',
                'method' => 'login',
                'panel' => 'C',
                'status' => 'A',
            ),
            31 => 
            array (
                'res_id' => 'BF',
                'title' => 'Endpoint',
                'controller_title' => 'Social',
                'directory' => '',
                'controller' => 'social',
                'method' => 'endpoint',
                'panel' => 'C',
                'status' => 'A',
            ),
            32 => 
            array (
                'res_id' => 'BG',
                'title' => 'Social Login Error',
                'controller_title' => 'Social',
                'directory' => '',
                'controller' => 'social',
                'method' => 'login-error',
                'panel' => 'C',
                'status' => 'A',
            ),
            33 => 
            array (
                'res_id' => 'BH',
                'title' => 'Client List',
                'controller_title' => '14. Client',
                'directory' => 'admin',
                'controller' => 'client',
                'method' => 'index',
                'panel' => 'A',
                'status' => 'A',
            ),
            34 => 
            array (
                'res_id' => 'BI',
                'title' => 'New Client',
                'controller_title' => '14. Client',
                'directory' => 'admin',
                'controller' => 'client',
                'method' => 'add',
                'panel' => 'A',
                'status' => 'A',
            ),
            35 => 
            array (
                'res_id' => 'BJ',
                'title' => 'Index',
                'controller_title' => 'Test',
                'directory' => '',
                'controller' => 'test',
                'method' => 'index',
                'panel' => 'C',
                'status' => 'A',
            ),
            36 => 
            array (
                'res_id' => 'BK',
                'title' => 'General Settings',
                'controller_title' => '02. Admin Setting',
                'directory' => 'admin',
                'controller' => 'admin-setting',
                'method' => 'general',
                'panel' => 'A',
                'status' => 'A',
            ),
            37 => 
            array (
                'res_id' => 'BL',
                'title' => 'General',
                'controller_title' => '02. Admin Setting',
                'directory' => 'admin',
                'controller' => 'admin-setting-confirm',
                'method' => 'general',
                'panel' => 'A',
                'status' => 'A',
            ),
            38 => 
            array (
                'res_id' => 'BM',
                'title' => 'S Auto Load Change',
                'controller_title' => 'App Setting',
                'directory' => 'admin',
                'controller' => 'app-setting-confirm',
                'method' => 's-auto-load-change',
                'panel' => 'A',
                'status' => 'S',
            ),
            39 => 
            array (
                'res_id' => 'BN',
                'title' => 'Edit Setting',
                'controller_title' => 'App Setting',
                'directory' => 'admin',
                'controller' => 'app-setting',
                'method' => 'edit',
                'panel' => 'A',
                'status' => 'H',
            ),
            40 => 
            array (
                'res_id' => 'BO',
                'title' => 'Modify',
                'controller_title' => '02. Admin Setting',
                'directory' => 'admin',
                'controller' => 'admin-setting-confirm',
                'method' => 'modify',
                'panel' => 'A',
                'status' => 'A',
            ),
            41 => 
            array (
                'res_id' => 'BP',
                'title' => 'New Ticket',
                'controller_title' => 'Ticket',
                'directory' => '',
                'controller' => 'ticket',
                'method' => 'open',
                'panel' => 'C',
                'status' => 'A',
            ),
            42 => 
            array (
                'res_id' => 'BQ',
                'title' => 'New Ticket',
                'controller_title' => 'Ticket',
                'directory' => '',
                'controller' => 'ticket',
                'method' => 'open',
                'panel' => 'C',
                'status' => 'A',
            ),
            43 => 
            array (
                'res_id' => 'BR',
                'title' => 'Other API Settings',
                'controller_title' => '03. API Setting',
                'directory' => 'admin',
                'controller' => 'api-setting',
                'method' => 'api',
                'panel' => 'A',
                'status' => 'A',
            ),
            44 => 
            array (
                'res_id' => 'BS',
                'title' => 'Custom Field List',
                'controller_title' => '02. Admin Setting',
                'directory' => 'admin',
                'controller' => 'custom-field',
                'method' => 'index',
                'panel' => 'A',
                'status' => 'A',
            ),
            45 => 
            array (
                'res_id' => 'BT',
                'title' => 'New Custom Field',
                'controller_title' => '02. Admin Setting',
                'directory' => 'admin',
                'controller' => 'custom-field',
                'method' => 'add',
                'panel' => 'A',
                'status' => 'A',
            ),
            46 => 
            array (
                'res_id' => 'BU',
                'title' => 'Edit Custom Field',
                'controller_title' => '02. Admin Setting',
                'directory' => 'admin',
                'controller' => 'custom-field',
                'method' => 'edit',
                'panel' => 'A',
                'status' => 'A',
            ),
            47 => 
            array (
                'res_id' => 'BV',
                'title' => 'Modify',
                'controller_title' => '03. API Setting',
                'directory' => 'admin',
                'controller' => 'api-setting-confirm',
                'method' => 'modify',
                'panel' => 'A',
                'status' => 'S',
            ),
            48 => 
            array (
                'res_id' => 'BW',
                'title' => 'Envato Setting',
                'controller_title' => '03. API Setting',
                'directory' => 'admin',
                'controller' => 'api-setting',
                'method' => 'process-api',
                'panel' => 'A',
                'status' => 'S',
            ),
            49 => 
            array (
                'res_id' => 'BX',
                'title' => 'Status Change',
                'controller_title' => '02. Admin Setting',
                'directory' => 'admin',
                'controller' => 'custom-field-confirm',
                'method' => 'status-change',
                'panel' => 'A',
                'status' => 'A',
            ),
            50 => 
            array (
                'res_id' => 'BY',
                'title' => 'Api Check',
                'controller_title' => 'Ticket',
                'directory' => '',
                'controller' => 'ticket',
                'method' => 'api-check',
                'panel' => 'C',
                'status' => 'A',
            ),
            51 => 
            array (
                'res_id' => 'BZ',
                'title' => 'Custom Field Delete',
                'controller_title' => '02. Admin Setting',
                'directory' => 'admin',
                'controller' => 'custom-field-confirm',
                'method' => 'custom-field-delete',
                'panel' => 'A',
                'status' => 'A',
            ),
            52 => 
            array (
                'res_id' => 'CA',
                'title' => 'Category Delete',
                'controller_title' => '12. Category',
                'directory' => 'admin',
                'controller' => 'category-confirm',
                'method' => 'category-delete',
                'panel' => 'A',
                'status' => 'A',
            ),
            53 => 
            array (
                'res_id' => 'CB',
                'title' => 'Index',
                'controller_title' => 'Test',
                'directory' => '',
                'controller' => 'test',
                'method' => 'index',
                'panel' => 'C',
                'status' => 'A',
            ),
            54 => 
            array (
                'res_id' => 'CC',
                'title' => 'Ticket Open By Guest',
                'controller_title' => 'Ticket',
                'directory' => '',
                'controller' => 'ticket',
                'method' => 'opened',
                'panel' => 'C',
                'status' => 'A',
            ),
            55 => 
            array (
                'res_id' => 'CD',
                'title' => 'My Tickets',
                'controller_title' => 'Panel',
                'directory' => 'client',
                'controller' => 'panel',
                'method' => 'dashboard',
                'panel' => 'C',
                'status' => 'A',
            ),
            56 => 
            array (
                'res_id' => 'CE',
                'title' => 'Ticket Tmp Img',
                'controller_title' => 'Ticket',
                'directory' => '',
                'controller' => 'ticket',
                'method' => 'ticket-tmp-img',
                'panel' => 'C',
                'status' => 'A',
            ),
            57 => 
            array (
                'res_id' => 'CF',
                'title' => 'My Tickets',
                'controller_title' => 'Panel',
                'directory' => 'client',
                'controller' => 'panel',
                'method' => 'profile',
                'panel' => 'C',
                'status' => 'A',
            ),
            58 => 
            array (
                'res_id' => 'CG',
                'title' => 'Active Ticket',
                'controller_title' => 'Ticket',
                'directory' => '',
                'controller' => 'ticket',
                'method' => 'active-tickets',
                'panel' => 'C',
                'status' => 'A',
            ),
            59 => 
            array (
                'res_id' => 'CH',
                'title' => 'Close Ticket',
                'controller_title' => 'Ticket',
                'directory' => '',
                'controller' => 'ticket',
                'method' => 'closed-tickets',
                'panel' => 'C',
                'status' => 'A',
            ),
            60 => 
            array (
                'res_id' => 'CI',
                'title' => 'Ticket Details',
                'controller_title' => 'Ticket',
                'directory' => '',
                'controller' => 'ticket',
                'method' => 'details',
                'panel' => 'C',
                'status' => 'A',
            ),
            61 => 
            array (
                'res_id' => 'CJ',
                'title' => 'Ticket Img',
                'controller_title' => 'Ticket',
                'directory' => '',
                'controller' => 'ticket',
                'method' => 'ticket-img',
                'panel' => 'C',
                'status' => 'A',
            ),
            62 => 
            array (
                'res_id' => 'CK',
                'title' => 'Field Deatils',
                'controller_title' => 'Ticket',
                'directory' => '',
                'controller' => 'ticket',
                'method' => 'field-deatils',
                'panel' => 'C',
                'status' => 'A',
            ),
            63 => 
            array (
                'res_id' => 'CL',
                'title' => 'Field Details',
                'controller_title' => 'Ticket',
                'directory' => '',
                'controller' => 'ticket',
                'method' => 'field-details',
                'panel' => 'C',
                'status' => 'A',
            ),
            64 => 
            array (
                'res_id' => 'CM',
                'title' => 'Ticket Reply',
                'controller_title' => 'Ticket',
                'directory' => '',
                'controller' => 'ticket-confirm',
                'method' => 'ticket-reply',
                'panel' => 'C',
                'status' => 'A',
            ),
            65 => 
            array (
                'res_id' => 'CN',
                'title' => 'Re Open',
                'controller_title' => 'Ticket',
                'directory' => '',
                'controller' => 'ticket',
                'method' => 're-open',
                'panel' => 'C',
                'status' => 'A',
            ),
            66 => 
            array (
                'res_id' => 'CO',
                'title' => 'Ticket Replied File',
                'controller_title' => 'Ticket',
                'directory' => '',
                'controller' => 'ticket',
                'method' => 'ticket-replied-file',
                'panel' => 'C',
                'status' => 'A',
            ),
            67 => 
            array (
                'res_id' => 'CP',
                'title' => 'Edit Ticket',
                'controller_title' => '10. Ticket',
                'directory' => 'admin',
                'controller' => 'ticket',
                'method' => 'edit',
                'panel' => 'A',
                'status' => 'H',
            ),
            68 => 
            array (
                'res_id' => 'CQ',
                'title' => 'Ticket Delete',
                'controller_title' => '10. Ticket',
                'directory' => 'admin',
                'controller' => 'ticket-confirm',
                'method' => 'ticket-delete',
                'panel' => 'A',
                'status' => 'A',
            ),
            69 => 
            array (
                'res_id' => 'CR',
                'title' => 'Closed Ticket List',
                'controller_title' => '10. Ticket',
                'directory' => 'admin',
                'controller' => 'ticket',
                'method' => 'closed-ticket',
                'panel' => 'A',
                'status' => 'A',
            ),
            70 => 
            array (
                'res_id' => 'CS',
                'title' => 'Assign Ticket',
                'controller_title' => '10. Ticket',
                'directory' => 'admin',
                'controller' => 'ticket',
                'method' => 'set-assign',
                'panel' => 'A',
                'status' => 'A',
            ),
            71 => 
            array (
                'res_id' => 'CT',
                'title' => 'Assign Me',
                'controller_title' => '10. Ticket',
                'directory' => 'admin',
                'controller' => 'ticket-confirm',
                'method' => 'assign-me',
                'panel' => 'A',
                'status' => 'A',
            ),
            72 => 
            array (
                'res_id' => 'CU',
                'title' => 'Paypal Settings',
                'controller_title' => '03. API Setting',
                'directory' => 'admin',
                'controller' => 'api-setting',
                'method' => 'paypal-setting',
                'panel' => 'A',
                'status' => 'A',
            ),
            73 => 
            array (
                'res_id' => 'CV',
                'title' => 'Update Paypal',
                'controller_title' => '03. API Setting',
                'directory' => 'admin',
                'controller' => 'api-setting-confirm',
                'method' => 'update-paypal',
                'panel' => 'A',
                'status' => 'S',
            ),
            74 => 
            array (
                'res_id' => 'CW',
                'title' => 'Social Settings',
                'controller_title' => '03. API Setting',
                'directory' => 'admin',
                'controller' => 'api-setting',
                'method' => 'social-setting',
                'panel' => 'A',
                'status' => 'A',
            ),
            75 => 
            array (
                'res_id' => 'CX',
                'title' => 'Update Social',
                'controller_title' => '03. API Setting',
                'directory' => 'admin',
                'controller' => 'api-setting-confirm',
                'method' => 'update-social',
                'panel' => 'A',
                'status' => 'S',
            ),
            76 => 
            array (
                'res_id' => 'CY',
                'title' => 'Email To Ticket Settings',
                'controller_title' => '02. Admin Setting',
                'directory' => 'admin',
                'controller' => 'admin-setting',
                'method' => 'imap',
                'panel' => 'A',
                'status' => 'A',
            ),
            77 => 
            array (
                'res_id' => 'CZ',
                'title' => 'Email To Ticket',
                'controller_title' => 'Cron',
                'directory' => 'autoscript',
                'controller' => 'cron',
                'method' => 'email-to-ticket',
                'panel' => 'C',
                'status' => 'A',
            ),
            78 => 
            array (
                'res_id' => 'DA',
                'title' => 'Email Templates List',
                'controller_title' => '02. Admin Setting',
                'directory' => 'admin',
                'controller' => 'email-templates',
                'method' => 'index',
                'panel' => 'A',
                'status' => 'A',
            ),
            79 => 
            array (
                'res_id' => 'DB',
                'title' => 'Update Email Template',
                'controller_title' => '02. Admin Setting',
                'directory' => 'admin',
                'controller' => 'email-templates',
                'method' => 'edit',
                'panel' => 'A',
                'status' => 'A',
            ),
            80 => 
            array (
                'res_id' => 'DC',
                'title' => 'Status Change',
                'controller_title' => '02. Admin Setting',
                'directory' => 'admin',
                'controller' => 'email-templates-confirm',
                'method' => 'status-change',
                'panel' => 'A',
                'status' => 'A',
            ),
            81 => 
            array (
                'res_id' => 'DD',
                'title' => 'User Ticket',
                'controller_title' => 'Ticket',
                'directory' => '',
                'controller' => 'ticket',
                'method' => 'user-ticket',
                'panel' => 'C',
                'status' => 'A',
            ),
            82 => 
            array (
                'res_id' => 'DE',
                'title' => 'Guest Ticket',
                'controller_title' => 'Ticket',
                'directory' => '',
                'controller' => 'ticket',
                'method' => 'guest-ticket',
                'panel' => 'C',
                'status' => 'A',
            ),
            83 => 
            array (
                'res_id' => 'DF',
                'title' => 'Email Outgoing Settings',
                'controller_title' => '02. Admin Setting',
                'directory' => 'admin',
                'controller' => 'admin-setting',
                'method' => 'email-out-settings',
                'panel' => 'A',
                'status' => 'A',
            ),
            84 => 
            array (
                'res_id' => 'DG',
                'title' => 'Debug Log List',
                'controller_title' => '07. App Information',
                'directory' => 'admin',
                'controller' => 'debug-log',
                'method' => 'index',
                'panel' => 'A',
                'status' => 'A',
            ),
            85 => 
            array (
                'res_id' => 'DH',
                'title' => 'Details Debug Log',
                'controller_title' => '07. App Information',
                'directory' => 'admin',
                'controller' => 'debug-log',
                'method' => 'view-dtls',
                'panel' => 'A',
                'status' => 'A',
            ),
            86 => 
            array (
                'res_id' => 'DI',
                'title' => 'Process',
                'controller_title' => 'Cron',
                'directory' => 'autoscript',
                'controller' => 'cron',
                'method' => 'process',
                'panel' => 'C',
                'status' => 'A',
            ),
            87 => 
            array (
                'res_id' => 'DJ',
                'title' => 'Edit Client',
                'controller_title' => '14. Client',
                'directory' => 'admin',
                'controller' => 'client',
                'method' => 'edit',
                'panel' => 'A',
                'status' => 'A',
            ),
            88 => 
            array (
                'res_id' => 'DK',
                'title' => 'Ticket Payment',
                'controller_title' => 'Ticket',
                'directory' => '',
                'controller' => 'ticket',
                'method' => 'ticket-payment',
                'panel' => 'C',
                'status' => 'A',
            ),
            89 => 
            array (
                'res_id' => 'DL',
                'title' => 'Paypal Payment Process',
                'controller_title' => 'Ticket',
                'directory' => '',
                'controller' => 'ticket',
                'method' => 'paypal-payment-process',
                'panel' => 'C',
                'status' => 'A',
            ),
            90 => 
            array (
                'res_id' => 'DM',
                'title' => 'System Update Process',
                'controller_title' => '07. App Information',
                'directory' => 'admin',
                'controller' => 'system-update',
                'method' => 'update',
                'panel' => 'A',
                'status' => 'H',
            ),
            91 => 
            array (
                'res_id' => 'DN',
                'title' => 'Application Update Info',
                'controller_title' => '07. App Information',
                'directory' => 'admin',
                'controller' => 'system-update',
                'method' => 'index',
                'panel' => 'A',
                'status' => 'A',
            ),
            92 => 
            array (
                'res_id' => 'DR',
                'title' => 'Ticket Details',
                'controller_title' => '10. Ticket',
                'directory' => 'admin',
                'controller' => 'ticket',
                'method' => 'details',
                'panel' => 'A',
                'status' => 'S',
            ),
            93 => 
            array (
                'res_id' => 'DS',
                'title' => 'Ticket Reply',
                'controller_title' => '10. Ticket',
                'directory' => 'admin',
                'controller' => 'ticket-confirm',
                'method' => 'ticket-reply',
                'panel' => 'A',
                'status' => 'A',
            ),
            94 => 
            array (
                'res_id' => 'DT',
                'title' => 'Knowledge List',
                'controller_title' => 'Knowledge',
                'directory' => '',
                'controller' => 'knowledge',
                'method' => 'index',
                'panel' => 'C',
                'status' => 'A',
            ),
            95 => 
            array (
                'res_id' => 'DU',
                'title' => 'Change Category',
                'controller_title' => '10. Ticket',
                'directory' => 'admin',
                'controller' => 'ticket',
                'method' => 'change-category',
                'panel' => 'A',
                'status' => 'S',
            ),
            96 => 
            array (
                'res_id' => 'DV',
                'title' => 'Menu List',
                'controller_title' => '02. Admin Setting',
                'directory' => 'admin',
                'controller' => 'menu',
                'method' => 'index',
                'panel' => 'A',
                'status' => 'A',
            ),
            97 => 
            array (
                'res_id' => 'DW',
                'title' => 'New Menu',
                'controller_title' => '02. Admin Setting',
                'directory' => 'admin',
                'controller' => 'menu',
                'method' => 'add',
                'panel' => 'A',
                'status' => 'A',
            ),
            98 => 
            array (
                'res_id' => 'DX',
                'title' => 'Menu Status Change',
                'controller_title' => '02. Admin Setting',
                'directory' => 'admin',
                'controller' => 'menu-confirm',
                'method' => 'status-change',
                'panel' => 'A',
                'status' => 'A',
            ),
            99 => 
            array (
                'res_id' => 'DY',
                'title' => 'Edit Menu',
                'controller_title' => '02. Admin Setting',
                'directory' => 'admin',
                'controller' => 'menu',
                'method' => 'edit',
                'panel' => 'A',
                'status' => 'A',
            ),
            100 => 
            array (
                'res_id' => 'DZ',
                'title' => 'Menu Delete',
                'controller_title' => '02. Admin Setting',
                'directory' => 'admin',
                'controller' => 'menu-confirm',
                'method' => 'menu-delete',
                'panel' => 'A',
                'status' => 'A',
            ),
            101 => 
            array (
                'res_id' => 'EA',
                'title' => 'New Window Status Change',
                'controller_title' => '02. Admin Setting',
                'directory' => 'admin',
                'controller' => 'menu-confirm',
                'method' => 'is-new-window-change',
                'panel' => 'A',
                'status' => 'A',
            ),
            102 => 
            array (
                'res_id' => 'EB',
                'title' => 'Topbar Icon List',
                'controller_title' => '02. Admin Setting',
                'directory' => 'admin',
                'controller' => 'topbar-icon',
                'method' => 'index',
                'panel' => 'A',
                'status' => 'A',
            ),
            103 => 
            array (
                'res_id' => 'EC',
                'title' => 'New Topbar Icon',
                'controller_title' => '02. Admin Setting',
                'directory' => 'admin',
                'controller' => 'topbar-icon',
                'method' => 'add',
                'panel' => 'A',
                'status' => 'A',
            ),
            104 => 
            array (
                'res_id' => 'ED',
                'title' => 'Topbar Icon Delete',
                'controller_title' => '02. Admin Setting',
                'directory' => 'admin',
                'controller' => 'topbar-icon-confirm',
                'method' => 'topbar-icon-delete',
                'panel' => 'A',
                'status' => 'A',
            ),
            105 => 
            array (
                'res_id' => 'EE',
                'title' => 'Topbar Icon Status Change',
                'controller_title' => '02. Admin Setting',
                'directory' => 'admin',
                'controller' => 'topbar-icon-confirm',
                'method' => 'status-change',
                'panel' => 'A',
                'status' => 'A',
            ),
            106 => 
            array (
                'res_id' => 'EF',
                'title' => 'Edit Topbar Icon',
                'controller_title' => '02. Admin Setting',
                'directory' => 'admin',
                'controller' => 'topbar-icon',
                'method' => 'edit',
                'panel' => 'A',
                'status' => 'A',
            ),
            107 => 
            array (
                'res_id' => 'EG',
                'title' => 'Search',
                'controller_title' => 'Site',
                'directory' => '',
                'controller' => 'site',
                'method' => 'search',
                'panel' => 'C',
                'status' => 'A',
            ),
            108 => 
            array (
                'res_id' => 'EH',
                'title' => 'Search Result',
                'controller_title' => 'Knowledge',
                'directory' => '',
                'controller' => 'knowledge',
                'method' => 'search-result',
                'panel' => 'C',
                'status' => 'A',
            ),
            109 => 
            array (
                'res_id' => 'EI',
                'title' => 'IP List',
                'controller_title' => '02. Admin Setting',
                'directory' => 'admin',
                'controller' => 'iplist',
                'method' => 'index',
                'panel' => 'A',
                'status' => 'A',
            ),
            110 => 
            array (
                'res_id' => 'EJ',
                'title' => 'New IP Entry',
                'controller_title' => '02. Admin Setting',
                'directory' => 'admin',
                'controller' => 'iplist',
                'method' => 'add',
                'panel' => 'A',
                'status' => 'A',
            ),
            111 => 
            array (
                'res_id' => 'EK',
                'title' => 'Ipblock',
                'controller_title' => 'App Secuity',
                'directory' => '',
                'controller' => 'App-secuity',
                'method' => 'ipblock',
                'panel' => 'C',
                'status' => 'A',
            ),
            112 => 
            array (
                'res_id' => 'EL',
                'title' => 'Support System',
                'controller_title' => 'App Security',
                'directory' => '',
                'controller' => 'App-security',
                'method' => 'ipblock',
                'panel' => 'C',
                'status' => 'A',
            ),
            113 => 
            array (
                'res_id' => 'EM',
                'title' => 'Ipblock',
                'controller_title' => 'Site Security',
                'directory' => '',
                'controller' => 'site-security',
                'method' => 'ipblock',
                'panel' => 'C',
                'status' => 'A',
            ),
            114 => 
            array (
                'res_id' => 'EN',
                'title' => 'My Ticket List',
                'controller_title' => '10. Ticket',
                'directory' => 'admin',
                'controller' => 'ticket',
                'method' => 'my-ticket',
                'panel' => 'A',
                'status' => 'S',
            ),
            115 => 
            array (
                'res_id' => 'EO',
                'title' => 'My Closed Ticket',
                'controller_title' => '10. Ticket',
                'directory' => 'admin',
                'controller' => 'ticket',
                'method' => 'my-closed',
                'panel' => 'A',
                'status' => 'S',
            ),
            116 => 
            array (
                'res_id' => 'EP',
                'title' => 'Security Settings',
                'controller_title' => '02. Admin Setting',
                'directory' => 'admin',
                'controller' => 'admin-setting',
                'method' => 'security',
                'panel' => 'A',
                'status' => 'A',
            ),
            117 => 
            array (
                'res_id' => 'EQ',
                'title' => 'Modify Security',
                'controller_title' => '02. Admin Setting',
                'directory' => 'admin',
                'controller' => 'admin-setting-confirm',
                'method' => 'modify-security',
                'panel' => 'A',
                'status' => 'A',
            ),
            118 => 
            array (
                'res_id' => 'ER',
                'title' => 'Locked User List',
                'controller_title' => '02. Admin Setting',
                'directory' => 'admin',
                'controller' => 'locked-user',
                'method' => 'index',
                'panel' => 'A',
                'status' => 'A',
            ),
            119 => 
            array (
                'res_id' => 'ES',
                'title' => 'Unlock Admin User',
                'controller_title' => '02. Admin Setting',
                'directory' => 'admin',
                'controller' => 'locked-user-confirm',
                'method' => 'locked-user-delete',
                'panel' => 'A',
                'status' => 'A',
            ),
            120 => 
            array (
                'res_id' => 'ET',
                'title' => 'Edit IP',
                'controller_title' => '02. Admin Setting',
                'directory' => 'admin',
                'controller' => 'iplist',
                'method' => 'edit',
                'panel' => 'A',
                'status' => 'A',
            ),
            121 => 
            array (
                'res_id' => 'EU',
                'title' => 'Block IP Reset',
                'controller_title' => '02. Admin Setting',
                'directory' => 'admin',
                'controller' => 'iplist-confirm',
                'method' => 'iplist-reset',
                'panel' => 'A',
                'status' => 'A',
            ),
            122 => 
            array (
                'res_id' => 'EV',
                'title' => 'System Message Dismiss',
                'controller_title' => '16.  System Message',
                'directory' => 'admin',
                'controller' => 'system-msg-confirm',
                'method' => 'system-msg-dismiss',
                'panel' => 'A',
                'status' => 'A',
            ),
            123 => 
            array (
                'res_id' => 'EW',
                'title' => 'Viewed',
                'controller_title' => 'Notification',
                'directory' => 'admin',
                'controller' => 'notification',
                'method' => 'viewed',
                'panel' => 'A',
                'status' => 'S',
            ),
            124 => 
            array (
                'res_id' => 'EX',
                'title' => 'Announcements List',
                'controller_title' => '09. Announcements',
                'directory' => 'admin',
                'controller' => 'notice',
                'method' => 'index',
                'panel' => 'A',
                'status' => 'A',
            ),
            125 => 
            array (
                'res_id' => 'EY',
                'title' => 'New Announcements',
                'controller_title' => '09. Announcements',
                'directory' => 'admin',
                'controller' => 'notice',
                'method' => 'add',
                'panel' => 'A',
                'status' => 'A',
            ),
            126 => 
            array (
                'res_id' => 'EZ',
                'title' => 'Edit Announcements',
                'controller_title' => '09. Announcements',
                'directory' => 'admin',
                'controller' => 'notice',
                'method' => 'edit',
                'panel' => 'A',
                'status' => 'A',
            ),
            127 => 
            array (
                'res_id' => 'FA',
                'title' => 'Admin Message List',
                'controller_title' => '15. Message',
                'directory' => 'admin',
                'controller' => 'admin-message',
                'method' => 'index',
                'panel' => 'A',
                'status' => 'S',
            ),
            128 => 
            array (
                'res_id' => 'FB',
                'title' => 'New Admin Message',
                'controller_title' => '15. Message',
                'directory' => 'admin',
                'controller' => 'admin-message',
                'method' => 'add',
                'panel' => 'A',
                'status' => 'S',
            ),
            129 => 
            array (
                'res_id' => 'FC',
                'title' => 'Sent Message By Me',
                'controller_title' => '15. Message',
                'directory' => 'admin',
                'controller' => 'admin-message',
                'method' => 'sent',
                'panel' => 'A',
                'status' => 'S',
            ),
            130 => 
            array (
                'res_id' => 'FD',
                'title' => 'Edit Admin Message',
                'controller_title' => '15. Message',
                'directory' => 'admin',
                'controller' => 'admin-message',
                'method' => 'edit',
                'panel' => 'A',
                'status' => 'A',
            ),
            131 => 
            array (
                'res_id' => 'FE',
                'title' => 'Announcements Status Change',
                'controller_title' => '09. Announcements',
                'directory' => 'admin',
                'controller' => 'notice-confirm',
                'method' => 'status-change',
                'panel' => 'A',
                'status' => 'A',
            ),
            132 => 
            array (
                'res_id' => 'FF',
                'title' => 'New Email Templates',
                'controller_title' => '02. Admin Setting',
                'directory' => 'admin',
                'controller' => 'email-templates',
                'method' => 'add',
                'panel' => 'A',
                'status' => 'H',
            ),
            133 => 
            array (
                'res_id' => 'FG',
                'title' => 'Details',
                'controller_title' => '15. Message',
                'directory' => 'admin',
                'controller' => 'admin-message',
                'method' => 'details',
                'panel' => 'A',
                'status' => 'S',
            ),
            134 => 
            array (
                'res_id' => 'FH',
                'title' => 'Reply',
                'controller_title' => '15. Message',
                'directory' => 'admin',
                'controller' => 'admin-message-confirm',
                'method' => 'reply',
                'panel' => 'A',
                'status' => 'S',
            ),
            135 => 
            array (
                'res_id' => 'FI',
                'title' => 'Show',
                'controller_title' => 'Notification',
                'directory' => 'admin',
                'controller' => 'notification',
                'method' => 'show',
                'panel' => 'A',
                'status' => 'S',
            ),
            136 => 
            array (
                'res_id' => 'FJ',
                'title' => 'Notification List',
                'controller_title' => 'Notification',
                'directory' => 'admin',
                'controller' => 'notification',
                'method' => 'show-list',
                'panel' => 'A',
                'status' => 'S',
            ),
            137 => 
            array (
                'res_id' => 'FK',
                'title' => 'Change User Status',
                'controller_title' => '05. User Settings',
                'directory' => 'admin',
                'controller' => 'app-permission-confirm',
                'method' => 'change-user-status',
                'panel' => 'A',
                'status' => 'A',
            ),
            138 => 
            array (
                'res_id' => 'FL',
                'title' => 'Reset User Pass',
                'controller_title' => '05. User Settings',
                'directory' => 'admin',
                'controller' => 'app-permission-confirm',
                'method' => 'reset-user-pass',
                'panel' => 'A',
                'status' => 'A',
            ),
            139 => 
            array (
                'res_id' => 'FM',
                'title' => 'Application Update Process',
                'controller_title' => '07. App Information',
                'directory' => 'admin',
                'controller' => 'system-update',
                'method' => 'process-update',
                'panel' => 'A',
                'status' => 'A',
            ),
            140 => 
            array (
                'res_id' => 'FN',
                'title' => 'System Updating',
                'controller_title' => '07. App Information',
                'directory' => 'admin',
                'controller' => 'system-update',
                'method' => 'updating',
                'panel' => 'A',
                'status' => 'S',
            ),
            141 => 
            array (
                'res_id' => 'FO',
                'title' => 'Test',
                'controller_title' => '07. App Information',
                'directory' => 'admin',
                'controller' => 'system-update',
                'method' => 'test',
                'panel' => 'A',
                'status' => 'H',
            ),
            142 => 
            array (
                'res_id' => 'FP',
                'title' => 'Feedback',
                'controller_title' => 'Ticket',
                'directory' => '',
                'controller' => 'ticket',
                'method' => 'feedback',
                'panel' => 'C',
                'status' => 'A',
            ),
            143 => 
            array (
                'res_id' => 'FQ',
                'title' => 'Re Open',
                'controller_title' => '10. Ticket',
                'directory' => 'admin',
                'controller' => 'ticket',
                'method' => 're-open',
                'panel' => 'A',
                'status' => 'A',
            ),
            144 => 
            array (
                'res_id' => 'FR',
                'title' => 'Knowledge List',
                'controller_title' => 'Category',
                'directory' => '',
                'controller' => 'category',
                'method' => 'index',
                'panel' => 'C',
                'status' => 'A',
            ),
            145 => 
            array (
                'res_id' => 'FS',
                'title' => 'Not Found',
                'controller_title' => 'Category',
                'directory' => '',
                'controller' => 'category',
                'method' => 'details',
                'panel' => 'C',
                'status' => 'A',
            ),
            146 => 
            array (
                'res_id' => 'FT',
                'title' => 'Theme Settings',
                'controller_title' => '02. Admin Setting',
                'directory' => 'admin',
                'controller' => 'admin-setting',
                'method' => 'theme',
                'panel' => 'A',
                'status' => 'A',
            ),
            147 => 
            array (
                'res_id' => 'FU',
                'title' => 'Modify Theme',
                'controller_title' => '02. Admin Setting',
                'directory' => 'admin',
                'controller' => 'admin-setting-confirm',
                'method' => 'modify-theme',
                'panel' => 'A',
                'status' => 'A',
            ),
            148 => 
            array (
                'res_id' => 'FV',
                'title' => 'Upload',
                'controller_title' => 'Image Upload',
                'directory' => 'admin',
                'controller' => 'image-upload',
                'method' => 'upload',
                'panel' => 'A',
                'status' => 'S',
            ),
            149 => 
            array (
                'res_id' => 'FW',
                'title' => 'Manager',
                'controller_title' => 'Image Upload',
                'directory' => 'admin',
                'controller' => 'image-upload',
                'method' => 'manager',
                'panel' => 'A',
                'status' => 'S',
            ),
            150 => 
            array (
                'res_id' => 'FX',
                'title' => 'Delete',
                'controller_title' => 'Image Upload',
                'directory' => 'admin',
                'controller' => 'image-upload',
                'method' => 'delete',
                'panel' => 'A',
                'status' => 'S',
            ),
            151 => 
            array (
                'res_id' => 'FY',
                'title' => 'Delete Feature',
                'controller_title' => '11. Knowledge',
                'directory' => 'admin',
                'controller' => 'knowledge-confirm',
                'method' => 'delete-feature',
                'panel' => 'A',
                'status' => 'S',
            ),
            152 => 
            array (
                'res_id' => 'FZ',
                'title' => 'My Paid Ticket',
                'controller_title' => '10. Ticket',
                'directory' => 'admin',
                'controller' => 'ticket',
                'method' => 'my-paid-ticket',
                'panel' => 'A',
                'status' => 'S',
            ),
            153 => 
            array (
                'res_id' => 'GA',
                'title' => 'All Paid Ticket',
                'controller_title' => '10. Ticket',
                'directory' => 'admin',
                'controller' => 'ticket',
                'method' => 'all-paid-ticket',
                'panel' => 'A',
                'status' => 'A',
            ),
            154 => 
            array (
                'res_id' => 'GB',
                'title' => 'My Assigned All Tickets',
                'controller_title' => '10. Ticket',
                'directory' => 'admin',
                'controller' => 'ticket',
                'method' => 'my-assigned-ticket',
                'panel' => 'A',
                'status' => 'A',
            ),
            155 => 
            array (
                'res_id' => 'GC',
                'title' => 'Server Requirment Failed',
                'controller_title' => 'Server Requiment',
                'directory' => '',
                'controller' => 'server-requiment',
                'method' => 'index',
                'panel' => 'C',
                'status' => 'A',
            ),
            156 => 
            array (
                'res_id' => 'GD',
                'title' => 'Resource Missmatch',
                'controller_title' => 'Server Requiment',
                'directory' => '',
                'controller' => 'server-requiment',
                'method' => 'resource-missmatch',
                'panel' => 'C',
                'status' => 'A',
            ),
            157 => 
            array (
                'res_id' => 'GE',
                'title' => 'Change Timezone',
                'controller_title' => '08. My Dashboard',
                'directory' => 'admin',
                'controller' => 'dashboard',
                'method' => 'set-timezone',
                'panel' => 'A',
                'status' => 'S',
            ),
            158 => 
            array (
                'res_id' => 'GF',
                'title' => 'Canned Msg List',
                'controller_title' => '13. Canned Msg',
                'directory' => 'admin',
                'controller' => 'canned-msg',
                'method' => 'index',
                'panel' => 'A',
                'status' => 'A',
            ),
            159 => 
            array (
                'res_id' => 'GG',
                'title' => 'New Canned Msg',
                'controller_title' => '13. Canned Msg',
                'directory' => 'admin',
                'controller' => 'canned-msg',
                'method' => 'add',
                'panel' => 'A',
                'status' => 'A',
            ),
            160 => 
            array (
                'res_id' => 'GH',
                'title' => 'Edit Canned Message',
                'controller_title' => '13. Canned Msg',
                'directory' => 'admin',
                'controller' => 'canned-msg',
                'method' => 'edit',
                'panel' => 'A',
                'status' => 'A',
            ),
            161 => 
            array (
                'res_id' => 'GI',
                'title' => 'Canned Msg Delete',
                'controller_title' => '13. Canned Msg',
                'directory' => 'admin',
                'controller' => 'canned-msg-confirm',
                'method' => 'canned-msg-delete',
                'panel' => 'A',
                'status' => 'A',
            ),
            162 => 
            array (
                'res_id' => 'GJ',
                'title' => 'Admin Dashboard',
                'controller_title' => '01. Admin Report',
                'directory' => 'admin',
                'controller' => 'admin-report',
                'method' => 'index',
                'panel' => 'A',
                'status' => 'A',
            ),
            163 => 
            array (
                'res_id' => 'GK',
                'title' => 'All Unassigned All Tickets',
                'controller_title' => '10. Ticket',
                'directory' => 'admin',
                'controller' => 'ticket',
                'method' => 'unassigned-ticket',
                'panel' => 'A',
                'status' => 'A',
            ),
            164 => 
            array (
                'res_id' => 'GL',
                'title' => 'Ticket Payment List',
                'controller_title' => '04. Payment List',
                'directory' => 'admin',
                'controller' => 'ticket-payment',
                'method' => 'index',
                'panel' => 'A',
                'status' => 'A',
            ),
            165 => 
            array (
                'res_id' => 'GM',
                'title' => 'Ticket Payment Details',
                'controller_title' => '04. Payment List',
                'directory' => 'admin',
                'controller' => 'ticket-payment',
                'method' => 'details',
                'panel' => 'A',
                'status' => 'A',
            ),
            166 => 
            array (
                'res_id' => 'GN',
                'title' => 'Ticket Feedback List',
                'controller_title' => '06. Ticket Feedback',
                'directory' => 'admin',
                'controller' => 'ticket-feedback',
                'method' => 'index',
                'panel' => 'A',
                'status' => 'A',
            ),
            167 => 
            array (
                'res_id' => 'GO',
                'title' => 'Details Info Of IP',
                'controller_title' => '02. Admin Setting',
                'directory' => 'admin',
                'controller' => 'iplist',
                'method' => 'detials',
                'panel' => 'A',
                'status' => 'S',
            ),
            168 => 
            array (
                'res_id' => 'GP',
                'title' => 'Sort Menu',
                'controller_title' => '05. User Settings',
                'directory' => 'admin',
                'controller' => 'app-permission',
                'method' => 'sort-controller-title',
                'panel' => 'A',
                'status' => 'H',
            ),
            169 => 
            array (
                'res_id' => 'GQ',
                'title' => 'Copy Role Access',
                'controller_title' => '05. User Settings',
                'directory' => 'admin',
                'controller' => 'app-permission',
                'method' => 'copy-access',
                'panel' => 'A',
                'status' => 'A',
            ),
            170 => 
            array (
                'res_id' => 'GR',
                'title' => 'Reset Role Access',
                'controller_title' => '05. User Settings',
                'directory' => 'admin',
                'controller' => 'app-permission',
                'method' => 'reset-access',
                'panel' => 'A',
                'status' => 'A',
            ),
            171 => 
            array (
                'res_id' => 'GS',
                'title' => 'Ticket Replied File',
                'controller_title' => 'Ticket',
                'directory' => 'admin',
                'controller' => 'ticket',
                'method' => 'ticket-replied-file',
                'panel' => 'A',
                'status' => 'S',
            ),
            172 => 
            array (
                'res_id' => 'GT',
                'title' => 'Is Stickey/Pinned Status Change',
                'controller_title' => '11. Knowledge',
                'directory' => 'admin',
                'controller' => 'knowledge-confirm',
                'method' => 'is-stickey-change',
                'panel' => 'A',
                'status' => 'A',
            ),
            173 => 
            array (
                'res_id' => 'GU',
                'title' => 'Re Check',
                'controller_title' => 'System Update',
                'directory' => 'admin',
                'controller' => 'system-update',
                'method' => 're-check',
                'panel' => 'A',
                'status' => 'S',
            ),
            174 => 
            array (
                'res_id' => 'GV',
                'title' => 'Status Change',
                'controller_title' => '13. Canned Msg',
                'directory' => 'admin',
                'controller' => 'canned-msg-confirm',
                'method' => 'status-change',
                'panel' => 'A',
                'status' => 'A',
            ),
            175 => 
            array (
                'res_id' => 'GW',
                'title' => 'Admin Notification Settings',
                'controller_title' => '02. Admin Setting',
                'directory' => 'admin',
                'controller' => 'admin-setting',
                'method' => 'notification',
                'panel' => 'A',
                'status' => 'A',
            ),
            176 => 
            array (
                'res_id' => 'GX',
                'title' => 'Modify Notification',
                'controller_title' => 'Admin Setting Confirm',
                'directory' => 'admin',
                'controller' => 'admin-setting-confirm',
                'method' => 'modify-notification',
                'panel' => 'A',
                'status' => 'S',
            ),
            177 => 
            array (
                'res_id' => 'GY',
                'title' => 'Notification',
                'controller_title' => 'Dashboard',
                'directory' => 'admin',
                'controller' => 'dashboard',
                'method' => 'notification',
                'panel' => 'A',
                'status' => 'S',
            ),
            178 => 
            array (
                'res_id' => 'HF',
                'title' => 'Client Profile',
                'controller_title' => 'Client',
                'directory' => 'admin',
                'controller' => 'client',
                'method' => 'profile',
                'panel' => 'A',
                'status' => 'S',
            ),
            179 => 
            array (
                'res_id' => 'HG',
                'title' => 'Ticket Img',
                'controller_title' => 'Ticket',
                'directory' => 'admin',
                'controller' => 'ticket',
                'method' => 'ticket-img',
                'panel' => 'A',
                'status' => 'S',
            ),
            180 => 
            array (
                'res_id' => 'HN',
                'title' => 'Set User Password',
                'controller_title' => '05. User Settings',
                'directory' => 'admin',
                'controller' => 'app-permission',
                'method' => 'set-user-pass',
                'panel' => 'A',
                'status' => 'S',
            ),
            181 => 
            array (
                'res_id' => 'HO',
                'title' => 'WebChat Panel',
                'controller_title' => '17. Web Chat',
                'directory' => 'admin',
                'controller' => 'admin-chat',
                'method' => 'index',
                'panel' => 'A',
                'status' => 'A',
            ),
            182 => 
            array (
                'res_id' => 'HP',
                'title' => 'Chat Response',
                'controller_title' => '17. Web Chat',
                'directory' => 'admin',
                'controller' => 'admin-chat',
                'method' => 'chat-response',
                'panel' => 'A',
                'status' => 'S',
            ),
            183 => 
            array (
                'res_id' => 'HQ',
                'title' => 'User Chat Close',
                'controller_title' => '17. Web Chat',
                'directory' => 'admin',
                'controller' => 'admin-chat-confirm',
                'method' => 'user-chat-close',
                'panel' => 'A',
                'status' => 'S',
            ),
            184 => 
            array (
                'res_id' => 'HR',
                'title' => 'User Answer',
                'controller_title' => '17. Web Chat',
                'directory' => 'admin',
                'controller' => 'admin-chat-confirm',
                'method' => 'user-answer',
                'panel' => 'A',
                'status' => 'S',
            ),
            185 => 
            array (
                'res_id' => 'HS',
                'title' => 'Edit Chat Canned Message',
                'controller_title' => '17. Web Chat',
                'directory' => 'admin',
                'controller' => 'chat-canned-msg',
                'method' => 'edit',
                'panel' => 'A',
                'status' => 'A',
            ),
            186 => 
            array (
                'res_id' => 'HT',
                'title' => 'New Chat Canned Msg',
                'controller_title' => '17. Web Chat',
                'directory' => 'admin',
                'controller' => 'chat-canned-msg',
                'method' => 'add',
                'panel' => 'A',
                'status' => 'A',
            ),
            187 => 
            array (
                'res_id' => 'HU',
                'title' => 'Chat Canned Msg List',
                'controller_title' => '17. Web Chat',
                'directory' => 'admin',
                'controller' => 'chat-canned-msg',
                'method' => 'index',
                'panel' => 'A',
                'status' => 'A',
            ),
            188 => 
            array (
                'res_id' => 'HV',
                'title' => 'New Admin Note',
                'controller_title' => 'Admin Note',
                'directory' => 'admin',
                'controller' => 'admin-note',
                'method' => 'add',
                'panel' => 'A',
                'status' => 'S',
            ),
            189 => 
            array (
                'res_id' => 'HW',
                'title' => 'Get Notes',
                'controller_title' => 'Admin Note',
                'directory' => 'admin',
                'controller' => 'admin-note',
                'method' => 'get-notes',
                'panel' => 'A',
                'status' => 'S',
            ),
            190 => 
            array (
                'res_id' => 'HX',
                'title' => 'Chat Settings',
                'controller_title' => '02. Admin Setting',
                'directory' => 'admin',
                'controller' => 'admin-setting',
                'method' => 'webchat-settings',
                'panel' => 'A',
                'status' => 'A',
            ),
            191 => 
            array (
                'res_id' => 'HY',
                'title' => 'Reset User Pass',
                'controller_title' => '14. Client',
                'directory' => 'admin',
                'controller' => 'client-confirm',
                'method' => 'reset-user-pass',
                'panel' => 'A',
                'status' => 'A',
            ),
            192 => 
            array (
                'res_id' => 'HZ',
                'title' => 'Update Chat Status',
                'controller_title' => 'Dashboard',
                'directory' => 'admin',
                'controller' => 'dashboard',
                'method' => 'update-chat-status',
                'panel' => 'A',
                'status' => 'S',
            ),
            193 => 
            array (
                'res_id' => 'IA',
                'title' => 'Update Notification Trey',
                'controller_title' => 'Dashboard',
                'directory' => 'admin',
                'controller' => 'dashboard',
                'method' => 'update-notification-trey',
                'panel' => 'A',
                'status' => 'S',
            ),
            194 => 
            array (
                'res_id' => 'IB',
                'title' => 'Delete Attach File',
                'controller_title' => '11. Knowledge',
                'directory' => 'admin',
                'controller' => 'knowledge-confirm',
                'method' => 'del-attach-file',
                'panel' => 'A',
                'status' => 'A',
            ),
            195 => 
            array (
                'res_id' => 'IC',
                'title' => 'Edit Ticket Reply',
                'controller_title' => '10. Ticket',
                'directory' => 'admin',
                'controller' => 'ticket',
                'method' => 'edit-reply',
                'panel' => 'A',
                'status' => 'S',
            ),
            196 => 
            array (
                'res_id' => 'ID',
                'title' => 'Load Ticket Reply',
                'controller_title' => '10. Ticket',
                'directory' => 'admin',
                'controller' => 'ticket',
                'method' => 'load-ticket-reply',
                'panel' => 'A',
                'status' => 'S',
            ),
            197 => 
            array (
                'res_id' => 'IE',
                'title' => 'Ticket Open By Admin',
                'controller_title' => '10. Ticket',
                'directory' => 'admin',
                'controller' => 'ticket',
                'method' => 'opened',
                'panel' => 'A',
                'status' => 'S',
            ),
            198 => 
            array (
                'res_id' => 'IF',
                'title' => 'Admin Ticket Creation',
                'controller_title' => '10. Ticket',
                'directory' => 'admin',
                'controller' => 'ticket',
                'method' => 'open',
                'panel' => 'A',
                'status' => 'A',
            ),
            199 => 
            array (
                'res_id' => 'IG',
                'title' => 'Ticket Assign Rule List',
                'controller_title' => '17. Ticket Assign Rule',
                'directory' => 'admin',
                'controller' => 'ticket-assign-rule',
                'method' => 'index',
                'panel' => 'A',
                'status' => 'A',
            ),
            200 => 
            array (
                'res_id' => 'IH',
                'title' => 'Edit Ticket Assign Rule',
                'controller_title' => '17. Ticket Assign Rule',
                'directory' => 'admin',
                'controller' => 'ticket-assign-rule',
                'method' => 'edit',
                'panel' => 'A',
                'status' => 'A',
            ),
            201 => 
            array (
                'res_id' => 'II',
                'title' => 'New Ticket Assign Rule',
                'controller_title' => '17. Ticket Assign Rule',
                'directory' => 'admin',
                'controller' => 'ticket-assign-rule',
                'method' => 'add',
                'panel' => 'A',
                'status' => 'A',
            ),
            202 => 
            array (
                'res_id' => 'IJ',
                'title' => '17. Ticket Assign Rule',
                'controller_title' => '17. Ticket Assign Rule',
                'directory' => 'admin',
                'controller' => 'ticket-assign-rule-confirm',
                'method' => 'ticket-assign-rule-delete',
                'panel' => 'A',
                'status' => 'A',
            ),
            203 => 
            array (
                'res_id' => 'IK',
                'title' => 'Status Change',
                'controller_title' => '17. Ticket Assign Rule',
                'directory' => 'admin',
                'controller' => 'ticket-assign-rule-confirm',
                'method' => 'status-change',
                'panel' => 'A',
                'status' => 'A',
            ),
            204 => 
            array (
                'res_id' => 'IL',
                'title' => 'Rate It',
                'controller_title' => 'System Update',
                'directory' => 'admin',
                'controller' => 'system-update',
                'method' => 'rate-it',
                'panel' => 'A',
                'status' => 'S',
            ),
            205 => 
            array (
                'res_id' => 'IM',
                'title' => 'Rate Status',
                'controller_title' => 'System Update',
                'directory' => 'admin',
                'controller' => 'system-update',
                'method' => 'rate-status',
                'panel' => 'A',
                'status' => 'S',
            ),
            206 => 
            array (
                'res_id' => 'IN',
                'title' => 'Please Rate It !!',
                'controller_title' => 'System Update',
                'directory' => 'admin',
                'controller' => 'system-update',
                'method' => 'thank-you',
                'panel' => 'A',
                'status' => 'S',
            ),
            207 => 
            array (
                'res_id' => 'IO',
                'title' => 'Remote Login List',
                'controller_title' => '03. API Setting',
                'directory' => 'admin',
                'controller' => 'remote-server',
                'method' => 'index',
                'panel' => 'A',
                'status' => 'A',
            ),
            208 => 
            array (
                'res_id' => 'IP',
                'title' => 'New Remote Login',
                'controller_title' => '03. API Setting',
                'directory' => 'admin',
                'controller' => 'remote-server',
                'method' => 'add',
                'panel' => 'A',
                'status' => 'A',
            ),
            209 => 
            array (
                'res_id' => 'IQ',
                'title' => 'Edit Remote Login',
                'controller_title' => '03. API Setting',
                'directory' => 'admin',
                'controller' => 'remote-server',
                'method' => 'edit',
                'panel' => 'A',
                'status' => 'A',
            ),
            210 => 
            array (
                'res_id' => 'IR',
                'title' => 'Delete Remote Login',
                'controller_title' => '03. API Setting',
                'directory' => 'admin',
                'controller' => 'remote-server-confirm',
                'method' => 'remote-server-delete',
                'panel' => 'A',
                'status' => 'A',
            ),
            211 => 
            array (
                'res_id' => 'IS',
                'title' => 'Remote Login Status Change',
                'controller_title' => '03. API Setting',
                'directory' => 'admin',
                'controller' => 'remote-server-confirm',
                'method' => 'status-change',
                'panel' => 'A',
                'status' => 'A',
            ),
            212 => 
            array (
                'res_id' => 'JE',
                'title' => 'New Work Log',
                'controller_title' => '10. Ticket',
                'directory' => 'admin',
                'controller' => 'work-log',
                'method' => 'add',
                'panel' => 'A',
                'status' => 'S',
            ),
            213 => 
            array (
                'res_id' => 'JF',
                'title' => 'Get Notes',
                'controller_title' => '10. Ticket',
                'directory' => 'admin',
                'controller' => 'work-log',
                'method' => 'get-notes',
                'panel' => 'A',
                'status' => 'S',
            ),
            214 => 
            array (
                'res_id' => 'JG',
                'title' => 'FAQ List',
                'controller_title' => '18. FAQ',
                'directory' => 'admin',
                'controller' => 'faq-lis',
                'method' => 'index',
                'panel' => 'A',
                'status' => 'A',
            ),
            215 => 
            array (
                'res_id' => 'JH',
                'title' => 'FAQ Add',
                'controller_title' => '18. FAQ',
                'directory' => 'admin',
                'controller' => 'faq-lis',
                'method' => 'add',
                'panel' => 'A',
                'status' => 'A',
            ),
            216 => 
            array (
                'res_id' => 'JI',
                'title' => 'FAQ edit',
                'controller_title' => '18. FAQ',
                'directory' => 'admin',
                'controller' => 'faq-lis',
                'method' => 'edit',
                'panel' => 'A',
                'status' => 'A',
            ),
            217 => 
            array (
                'res_id' => 'JJ',
                'title' => 'FAQ Category List',
                'controller_title' => '18. FAQ',
                'directory' => 'admin',
                'controller' => 'faq-category',
                'method' => 'index',
                'panel' => 'A',
                'status' => 'A',
            ),
            218 => 
            array (
                'res_id' => 'JK',
                'title' => 'FAQ Category Add',
                'controller_title' => '18. FAQ',
                'directory' => 'admin',
                'controller' => 'faq-category',
                'method' => 'add',
                'panel' => 'A',
                'status' => 'A',
            ),
            219 => 
            array (
                'res_id' => 'JL',
                'title' => 'FAQ Category Edit',
                'controller_title' => '18. FAQ',
                'directory' => 'admin',
                'controller' => 'faq-category',
                'method' => 'edit',
                'panel' => 'A',
                'status' => 'A',
            ),
            220 => 
            array (
                'res_id' => 'JM',
                'title' => 'FAQ Category Status Change',
                'controller_title' => '18. FAQ',
                'directory' => 'admin',
                'controller' => 'faq-category-confirm',
                'method' => 'status-change',
                'panel' => 'A',
                'status' => 'A',
            ),
            221 => 
            array (
                'res_id' => 'JN',
                'title' => 'Testimonial List',
                'controller_title' => '19. Testimonial',
                'directory' => 'admin',
                'controller' => 'testimonial',
                'method' => 'index',
                'panel' => 'A',
                'status' => 'A',
            ),
            222 => 
            array (
                'res_id' => 'JO',
                'title' => 'Testimonial Add',
                'controller_title' => '19. Testimonial',
                'directory' => 'admin',
                'controller' => 'testimonial',
                'method' => 'add',
                'panel' => 'A',
                'status' => 'A',
            ),
            223 => 
            array (
                'res_id' => 'JP',
                'title' => 'Testimonial Edit',
                'controller_title' => '19. Testimonial',
                'directory' => 'admin',
                'controller' => 'testimonial',
                'method' => 'edit',
                'panel' => 'A',
                'status' => 'A',
            ),
            224 => 
            array (
                'res_id' => 'JQ',
                'title' => 'Testimonial Status Change',
                'controller_title' => '19. Testimonial',
                'directory' => 'admin',
                'controller' => 'testimonial-confirm',
                'method' => 'status-change',
                'panel' => 'A',
                'status' => 'A',
            ),
            225 => 
            array (
                'res_id' => 'JR',
                'title' => 'Admin Addons page',
                'controller_title' => '19. Admin Addons page',
                'directory' => 'admin',
                'controller' => 'addons',
                'method' => 'admin-page',
                'panel' => 'A',
                'status' => 'S',
            ),
            226 => 
            array (
                'res_id' => 'JS',
                'title' => 'Update Payment Basic',
                'controller_title' => '3. payment Settings',
                'directory' => 'admin',
                'controller' => 'api-setting-confirm',
                'method' => 'update-payment-basic',
                'panel' => 'A',
                'status' => 'S',
            ),
            227 => 
            array (
                'res_id' => 'JT',
                'title' => 'Basic Settings',
                'controller_title' => '03. Payment Setting',
                'directory' => 'admin',
                'controller' => 'api-setting',
                'method' => 'payment-basic',
                'panel' => 'A',
                'status' => 'A',
            ),
            228 => 
            array (
                'res_id' => 'JU',
                'title' => 'Change Priority',
                'controller_title' => '10. Ticket',
                'directory' => 'admin',
                'controller' => 'ticket',
                'method' => 'change-priority',
                'panel' => 'A',
                'status' => 'S',
            ),
            229 => 
            array (
                'res_id' => 'JV',
                'title' => 'Close Ticket Without Reply',
                'controller_title' => '10. Ticket',
                'directory' => 'admin',
                'controller' => 'ticket-confirm',
                'method' => 'close-ticket',
                'panel' => 'A',
                'status' => 'S',
            ),
        ));
        
        
    }
}